import SwiftUI
import SwiftData
import ImagePlayground

/// Minimal settings: the notifications toggle and system permission.
struct SettingsView: View {
    @Environment(\.modelContext) private var modelContext
    @State private var viewModel = SettingsViewModel()
    @State private var isShowingWidgetGuide = false
    @Query(sort: \VocabularyWord.createdAt, order: .reverse) private var words: [VocabularyWord]

    private var widgetPreview: WidgetPreviewContent {
        guard let word = words.first(where: {
            $0.languageCode == viewModel.learningLanguageCode
        }) else { return .placeholder }
        return WidgetPreviewContent(word: word.word, translation: word.translation)
    }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    AddWidgetEntryCard(preview: widgetPreview) {
                        isShowingWidgetGuide = true
                    }
                    .listRowInsets(EdgeInsets())
                    .listRowBackground(Color.clear)
                }

                Section {
                    Picker("settings.learning_language", selection: $viewModel.learningLanguageCode) {
                        ForEach(viewModel.availableLanguages) { language in
                            Text(language.name).tag(language.code)
                        }
                    }
                    .onChange(of: viewModel.learningLanguageCode) {
                        WidgetSync.update(context: modelContext)
                    }

                    Picker("settings.native_language", selection: $viewModel.translationLanguageCode) {
                        ForEach(viewModel.availableLanguages.filter { $0.code != viewModel.learningLanguageCode }) { language in
                            Text(language.name).tag(language.code)
                        }
                    }
                } header: {
                    Text("settings.languages")
                } footer: {
                    if viewModel.learningLanguageCode == viewModel.translationLanguageCode {
                        Text("settings.same_language_error")
                            .foregroundStyle(.red)
                    } else {
                        Text("settings.language_pair_footer")
                    }
                }

                Section {
                    Toggle("settings.notifications", isOn: $viewModel.notificationsEnabled)
                        .onChange(of: viewModel.notificationsEnabled) {
                            viewModel.applyNotificationsSetting(context: modelContext)
                        }

                    LabeledContent("settings.permission", value: viewModel.permissionStatusDescription)

                    Button("settings.request_permission") {
                        Task { await viewModel.requestPermission() }
                    }
                } header: {
                    Text("settings.notifications")
                } footer: {
                    Text("settings.notifications_footer")
                }

                if AppFeatures.imageGenerationEnabled {
                    Section {
                        OnDeviceGenerationStatusRow()

                        TextField("AI Horde API key (optional)", text: $viewModel.aiHordeAPIKey)
                            .textInputAutocapitalization(.never)
                            .autocorrectionDisabled()

                        Button {
                            Task { await viewModel.verifyAPIKey() }
                        } label: {
                            if viewModel.isVerifyingAPIKey {
                                ProgressView()
                            } else {
                                Text("settings.verify_key")
                            }
                        }
                        .disabled(viewModel.isVerifyingAPIKey)

                        if let apiKeyStatus = viewModel.apiKeyStatus {
                            Text(apiKeyStatus)
                                .font(.footnote)
                                .foregroundStyle(.secondary)
                        }

                        Link("Get a free key at aihorde.net",
                             destination: URL(string: "https://aihorde.net/register") ?? URL(fileURLWithPath: "/"))
                    } header: {
                        Text("settings.image_generation")
                    } footer: {
                        Text("""
                        Scene images are generated by the free AI Horde network. \
                        Without a key requests wait in the slowest queue — \
                        a free personal key makes generation much faster.
                        """)
                    }
                }

                #if DEBUG
                Section("settings.development") {
                    Button("settings.reset_onboarding") {
                        OnboardingStore.resetForDevelopment()
                    }
                }
                #endif
            }
            .scrollContentBackground(.hidden)
            .background(AppBackgroundGradient())
            .navigationTitle("settings.title")
            .task {
                await viewModel.refreshPermissionStatus()
            }
            .sheet(isPresented: $isShowingWidgetGuide) {
                WidgetOnboardingView(preview: widgetPreview) {
                    WidgetPromotionStore.dismiss()
                }
                .presentationDetents([.large])
                .presentationDragIndicator(.visible)
            }
        }
        .tint(.lavender)
    }
}

/// Shows whether Image Playground (Apple Intelligence) can be used
/// on this device — handy for diagnosing why scene images fall back
/// to the network generator.
private struct OnDeviceGenerationStatusRow: View {
    var body: some View {
        if #available(iOS 18.2, *) {
            ImagePlaygroundStatusRow()
        } else {
            LabeledContent("On-device generation", value: "Requires iOS 18.2+")
        }
    }
}

@available(iOS 18.2, *)
private struct ImagePlaygroundStatusRow: View {
    @Environment(\.supportsImagePlayground) private var supportsImagePlayground

    var body: some View {
        LabeledContent(
            "On-device generation",
            value: supportsImagePlayground ? "Available" : "Unavailable"
        )
    }
}

#Preview {
    SettingsView()
        .modelContainer(for: VocabularyWord.self, inMemory: true)
}
