import SwiftUI
import SwiftData
import ImagePlayground

/// Minimal settings: the notifications toggle and system permission.
struct SettingsView: View {
    @Environment(\.modelContext) private var modelContext
    @State private var viewModel = SettingsViewModel()

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    Toggle("Review reminders", isOn: $viewModel.notificationsEnabled)
                        .onChange(of: viewModel.notificationsEnabled) {
                            viewModel.applyNotificationsSetting(context: modelContext)
                        }

                    LabeledContent("Permission", value: viewModel.permissionStatusDescription)

                    Button("Request notification permission") {
                        Task { await viewModel.requestPermission() }
                    }
                } header: {
                    Text("Notifications")
                } footer: {
                    Text("Lucius sends a gentle reminder when a word is ready for review — right when spaced repetition works best.")
                }

                if AppFeatures.imageGenerationEnabled {
                    Section {
                        OnDeviceGenerationStatusRow()

                        TextField("AI Horde API key (optional)", text: $viewModel.aiHordeAPIKey)
                            .textInputAutocapitalization(.never)
                            .autocorrectionDisabled()

                        Button {
                            Task { await viewModel.verifyAPIKey() }
                        } label: {
                            if viewModel.isVerifyingAPIKey {
                                ProgressView()
                            } else {
                                Text("Verify key")
                            }
                        }
                        .disabled(viewModel.isVerifyingAPIKey)

                        if let apiKeyStatus = viewModel.apiKeyStatus {
                            Text(apiKeyStatus)
                                .font(.footnote)
                                .foregroundStyle(.secondary)
                        }

                        Link("Get a free key at aihorde.net",
                             destination: URL(string: "https://aihorde.net/register") ?? URL(fileURLWithPath: "/"))
                    } header: {
                        Text("Image generation")
                    } footer: {
                        Text("""
                        Scene images are generated by the free AI Horde network. \
                        Without a key requests wait in the slowest queue — \
                        a free personal key makes generation much faster.
                        """)
                    }
                }
            }
            .scrollContentBackground(.hidden)
            .background(AppBackgroundGradient())
            .navigationTitle("Settings")
            .task {
                await viewModel.refreshPermissionStatus()
            }
        }
        .tint(.lavender)
    }
}

/// Shows whether Image Playground (Apple Intelligence) can be used
/// on this device — handy for diagnosing why scene images fall back
/// to the network generator.
private struct OnDeviceGenerationStatusRow: View {
    var body: some View {
        if #available(iOS 18.2, *) {
            ImagePlaygroundStatusRow()
        } else {
            LabeledContent("On-device generation", value: "Requires iOS 18.2+")
        }
    }
}

@available(iOS 18.2, *)
private struct ImagePlaygroundStatusRow: View {
    @Environment(\.supportsImagePlayground) private var supportsImagePlayground

    var body: some View {
        LabeledContent(
            "On-device generation",
            value: supportsImagePlayground ? "Available" : "Unavailable"
        )
    }
}

#Preview {
    SettingsView()
        .modelContainer(for: VocabularyWord.self, inMemory: true)
}
